version: "3.3"
services:
  dcrest:
    image: "firstklaas/digicubes-rest:latest"
    ports:
        - "3548:3548"
    container_name: digicubes_rest
    environment:
        DIGICUBES_DATABASE_URL: sqlite://data/digicubes.db
        DIGICUBES_SECRET: b3j6casjk7d8szeuwz00hdhuw4ohwDu9o
    volumes:
        - dbdata:/digicubes/data
    restart: always     
    
  digicubes-web:
    container_name: digicubes_web
    image: "firstklaas/digicubes-web:latest"
    ports:
        - "5555:5000"
    environment: 
        DC_API_SERVER_PROTOCOL: http
        DC_API_SERVER_HOST: dcrest
        DC_API_SERVER_PORT: 3548

    depends_on:
        - dcrest
    restart: always     

volumes: 
    dbdata:
        external: false
