version: "3.3"
services:
  digicubes-rest:
    image: "firstklaas/digicubes-rest:latest"
    container_name: digicubes_rest
    environment:
        DIGICUBES_DATABASE_URL: sqlite://data/digicubes.db
        DIGICUBES_SECRET: b3j6casjk7d8szeuwz00hdhuw4ohwDu9o
    volumes:
        - dbdata:/digicubes/data
    restart: always     
    
  digicubes-web:
    container_name: digicubes_web
    image: "firstklaas/digicubes-web:latest"
    ports:
        - "5000:5000"
    environment: 
        DC_API_SERVER_PROTOCOL: http
        DC_API_SERVER_HOST: nebuhrhood
        DC_API_SERVER_PORT: 3000

    depends_on:
        - digicubes-rest
    restart: always     

volumes: 
    dbdata:
        external: false
