secret: "djsjah67sh7/&)788hxcbxsh"

TOKEN_COOKIE_NAME: "digicubes.token"
TOKEN_SESSION_NAME: "digicubes.account"

# Account space
# -------------
DIGICUBES_ACCOUNT_URL_PREFIX: "/account"

# The route, that dispatches to the right homepage
# if the user has more than one role. Otherwise
# chains to the homepage for his role.  
DIGICUBES_DISPATCHER_VIEW: "account.home"

# If true, new users are verified automatically
# after registration
DIGICUBES_ACCOUNT_AUTO_VERIFY: true

DIGICUBES_API_SERVER_PROTOCOL: "http"
DIGICUBES_API_SERVER_HOSTNAME: "localhost"
DIGICUBES_API_SERVER_PORT: 3000

smtp_host: !ENV ${DC_SMTP_HOST}
smtp_port: !ENV ${DC_SMTP_PORT}
smtp_use_ssl: true
smtp_username: !ENV ${DC_SMTP_USERNAME}
smtp_password: !ENV ${DC_SMTP_PASSWORD}
smtp_from_email_addr: !ENV ${DC_FROM_EMAIL_ADDR}
smtp_from_display_name: !ENV ${DC_FROM_DISPLAY_NAME}
