
TOKEN_COOKIE_NAME: "digicubes.token"
TOKEN_SESSION_NAME: "digicubes.account"

# Account space
# -------------

DIGICUBES_ACCOUNT_URL_PREFIX: "/account"

# If true, new users are verified automatically
# after registration
DIGICUBES_ACCOUNT_AUTO_VERIFY: true

DIGICUBES_ACCOUNT_LOGIN_VIEW: "account.login"
DIGICUBES_ACCOUNT_REGISTER_VIEW: "account.register"
DIGICUBES_ACCOUNT_INDEX_VIEW: "account.index"

# Admin space
DIGICUBES_ADMIN_URL_PREFIX: "/admin"

DIGICUBES_API_SERVER_PROTOCOL: "http"
DIGICUBES_API_SERVER_HOSTNAME: "localhost"
DIGICUBES_API_SERVER_PORT: 3000
